<?php
/**
 * Default template part for restricted products.
 * 
 * @since CHANGEME
 * @version CHANGEME
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange_Addon_Membership
 * 
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's product to the exchange directory located
 * in your theme.
*/
?>

<?php do_action( 'it_exchange_membership_addon_product_restricted_before_wrap' ); ?>
<div id="it-exchange-product-restricted" class="it-exchange-wrap">
	<?php do_action( 'it_exchange_membership_addon_product_restricted_begin_wrap' ); ?>
	
	<?php it_exchange_get_template_part( 'messages' ); ?>
    
    <?php it_exchange( 'restricted', 'product' ); ?>
	
	<?php do_action( 'it_exchange_membership_addon_product_restricted_end_wrap' ); ?>
</div>
<?php do_action( 'it_exchange_membership_addon_product_restricted_after_wrap' ); ?>
